// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIHCFajA6G1js0yoX-wpxXBPchv-yqCo8',
    appId: '1:916679598679:web:7dc730be2cd481f0933912',
    messagingSenderId: '916679598679',
    projectId: 'somisoft-4e592',
    authDomain: 'somisoft-4e592.firebaseapp.com',
    storageBucket: 'somisoft-4e592.firebasestorage.app',
    measurementId: 'G-JMRFS9CRJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-OJ1Qfjz4YFcIYmCt27iAJEEnxndWO2I',
    appId: '1:916679598679:android:59c4d2827905b7a6933912',
    messagingSenderId: '916679598679',
    projectId: 'somisoft-4e592',
    storageBucket: 'somisoft-4e592.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMl4eAbexIvLlMQTIlv1cIbg0FxoOSgVI',
    appId: '1:916679598679:ios:b20b9abd434d2c67933912',
    messagingSenderId: '916679598679',
    projectId: 'somisoft-4e592',
    storageBucket: 'somisoft-4e592.firebasestorage.app',
    iosBundleId: 'com.example.simsoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMl4eAbexIvLlMQTIlv1cIbg0FxoOSgVI',
    appId: '1:916679598679:ios:b20b9abd434d2c67933912',
    messagingSenderId: '916679598679',
    projectId: 'somisoft-4e592',
    storageBucket: 'somisoft-4e592.firebasestorage.app',
    iosBundleId: 'com.example.simsoft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIHCFajA6G1js0yoX-wpxXBPchv-yqCo8',
    appId: '1:916679598679:web:30c4cd38d2553340933912',
    messagingSenderId: '916679598679',
    projectId: 'somisoft-4e592',
    authDomain: 'somisoft-4e592.firebaseapp.com',
    storageBucket: 'somisoft-4e592.firebasestorage.app',
    measurementId: 'G-X7W2PPDVY8',
  );
}
